version: '3.3'
services:
  node:
    container_name: project_node
    image: 'node:latest'
    working_dir: /home/node/app
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '8080:8080'
    volumes:
      - './api:/home/node/app'
      - '/home/node/app/node_modules'
    links:
      - mongo
    networks:
      - my-network
  front:
    container_name: project_front
    image: 'node:latest'
    working_dir: /home/node/app
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './front:/home/node/app'
      - '/home/node/app/node_modules'
    networks:
      - my-network
  mongo:
    container_name: project_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
